using System.Numerics;

namespace NumericTypesSuggester
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();
        }

        private void MainForm_Load(object sender, EventArgs e)
        {

        }

        private void IntegralOnlyCheckBox_Checked(object sender, EventArgs e)
        {
            MustBePreciseCheckbox.Visible = !IntegralOnlyCheckbox.Checked;

            RecalculateSuggestedType();
        }

        private void RecalculateSuggestedType()
        {
            if (IsInputComplete())
            {
                var minValue = BigInteger.Parse(
                    MinValueTextBox.Text);
                var maxValue = BigInteger.Parse(
                    MaxValueTextBox.Text);
                if(maxValue >= minValue)
                {
                    SuggestedTypeLabel.Text =
                        NumericTypeSuggester.GetName(
                            minValue,
                            maxValue,
                            IntegralOnlyCheckbox.Checked,
                            MustBePreciseCheckbox.Checked);
                    return;
                }

            }
            SuggestedTypeLabel.Text = "not enough data";
        }
        private void SetColorOfMaxValueTextField()
        {
            bool isValid = true;
            if (IsInputComplete())
            {
                var minValue = BigInteger.Parse(
                    MinValueTextBox.Text);
                var maxValue = BigInteger.Parse(
                    MaxValueTextBox.Text);

                if (maxValue < minValue)
                {
                    isValid = false;
                }
            }
            MaxValueTextBox.BackColor = isValid ? Color.White : Color.IndianRed;
        }

        private bool IsInputComplete()
        {
            return MinValueTextBox.Text.Length > 0 && MinValueTextBox.Text != "-" &&

            MaxValueTextBox.Text.Length > 0 && MaxValueTextBox.Text != "-";

           
        }

        private void MustBePreciseCheckbox_CheckedChanged(object sender, EventArgs e)
        {
            RecalculateSuggestedType();
        }

        private void TextBox_TextChanged(object sender, EventArgs e)
        {
            RecalculateSuggestedType();
            SetColorOfMaxValueTextField();
        }

        private void TextBox_KeyPress(object sender, KeyPressEventArgs e) //Renaming a method to include cahnge where method is used in the autogenerated klicka på metodnamnet och signaturen file Ctr + R + R
        {
            var textBox = (TextBox)sender;
            if (!IsValidInput(e.KeyChar, textBox))
            {
                e.Handled = true;
            }
        }

        private static bool IsValidInput(char keyChar, TextBox textBox)
        {
            return char.IsControl(keyChar) ||
                char.IsDigit(keyChar) ||
                (keyChar == '-' && textBox.SelectionStart == 0);
        }
    }
}
